volumes:
  nats_data:

networks:
  warehouse:
    driver: bridge

services:
  nats:
    image: nats:2.10-alpine3.21
    ports:
      - "4222:4222"
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"
    volumes:
      - nats_data:/data/jetstream
    networks:
      - warehouse
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -"]
      interval: 1s
      timeout: 5s
      retries: 5

  api-gateway:
    build: { args: { SERVICE: api_gateway } }
    ports:
      - "8080:8080"
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_API_PORT=8080
    volumes:
      - ./config.yml:/data/config.yml:ro
    networks:
      - warehouse
    depends_on:
      - nats

  warehouse-1:
    build: { args: { SERVICE: warehouse } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_WAREHOUSE_ID=1
    volumes:
      - ./config.yml:/data/config.yml
    networks:
      - warehouse
    depends_on:
      - nats

  warehouse-2:
    build: { args: { SERVICE: warehouse } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_WAREHOUSE_ID=2
    volumes:
      - ./config.yml:/data/config.yml
    networks:
      - warehouse
    depends_on:
      - nats

  catalog:
    build: { args: { SERVICE: catalog } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
    volumes:
      - ./config.yml:/data/config.yml
    networks:
      - warehouse
    depends_on:
      - nats

  order:
    build: { args: { SERVICE: order } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
    volumes:
      - ./config.yml:/data/config.yml
    networks:
      - warehouse
    depends_on:
      - nats

  authenticator:
    build: { args: { SERVICE: authenticator } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
    volumes:
      - ./config.yml:/data/config.yml
    networks:
      - warehouse
    depends_on:
      - nats
