volumes:
  nats_data:
  grafana_data:
  influxdb_data:


services:
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"
      - "--http_port=8222"
    volumes:
      - nats_data:/data/jetstream
    healthcheck:
      test: [ "CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -" ]
      interval: 1s
      timeout: 5s
      retries: 5

  api-gateway:
    build: { args: { SERVICE: api_gateway } }
    ports:
      - "8080:8080"
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_API_PORT=8080
      - OTLP_URL=collector:4317
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - ENV_SERVICE_ID=1
    depends_on:
      - nats

  warehouse-1:
    build: { args: { SERVICE: warehouse } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_SERVICE_ID=1
      - OTLP_URL=collector:4317
    depends_on:
      - nats

  warehouse-2:
    build: { args: { SERVICE: warehouse } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_SERVICE_ID=2
      - OTLP_URL=collector:4317
    depends_on:
      - nats

  catalog:
    build: { args: { SERVICE: catalog } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_SERVICE_ID=1
      - OTLP_URL=collector:4317
    depends_on:
      - nats

  order:
    build: { args: { SERVICE: order } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_SERVICE_ID=1
      - OTLP_URL=collector:4317
    depends_on:
      - nats

  authenticator:
    build: { args: { SERVICE: authenticator } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - OTLP_URL=collector:4317
      - ENV_SERVICE_ID=1
    depends_on:
      - nats

  influxdb:
    image: influxdb:alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=stockdb
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
  notification:
    build: { args: { SERVICE: notification } }
    environment:
      - INFLUXDB_TOKEN=my-token
      - INFLUXDB_ORG=my-org
      - ENV_BROKER_URL=nats://nats:4222
      - OTLP_URL=collector:4317
      - ENV_SERVICE_ID=1
      - RULE_CHECKER_TIMER=45
    depends_on:
      - nats
      - influxdb

  collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
    volumes:
      - ./containers/collector.yml:/etc/otelcol-contrib/config.yaml:ro
  loki:
    image: grafana/loki:3.4.2
  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-otlp-receiver"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./containers:/etc/grafana/provisioning
