volumes:
  nats_data:

networks:
  warehouse:
    driver: bridge

services:
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
    command:
      - "--jetstream"
      - "--store_dir=/data/jetstream"
    volumes:
      - nats_data:/data/jetstream
    networks:
      - warehouse
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -"]
      interval: 1s
      timeout: 5s
      retries: 5

  api-gateway:
    build: { args: { SERVICE: api_gateway } }
    ports:
      - "80:8080"
    environment:
      - ENV_BROKER_URL=nats://nats:4222
      - ENV_API_PORT=8080
    volumes:
      - ./config.yml:/data/config.yml:ro
    networks:
      - warehouse
    depends_on:
      - nats

  warehouse:
    build: { args: { SERVICE: warehouse } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
    volumes:
      - ./config.yml:/data/config.yml:ro
    networks:
      - warehouse
    depends_on:
      - nats

  catalog:
    build: { args: { SERVICE: catalog } }
    environment:
      - ENV_BROKER_URL=nats://nats:4222
    volumes:
      - ./config.yml:/data/config.yml:ro
    networks:
      - warehouse
    depends_on:
      - nats

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - warehouse
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=stockdb
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

  notification:
    build: { args: { SERVICE: notification } }
    environment:
      - INFLUXDB_TOKEN=my-token
      - ENV_BROKER_URL=nats://nats:4222
    networks:
      - warehouse
    depends_on:
      - nats
      - influxdb
