{
 "title": "Overview Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Warehouse-2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}"
    }
   ]
  },
  {
   "title": "Total Warehouse requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "num_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Stock Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "num_add_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remove Stock Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "num_remove_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Reservation Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "num_create_reservation_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Stock Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "num_update_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warehouse Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "num_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Reservation Event Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "num_reservation_event_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "num_update_order_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Good Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "num_update_good_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Update Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "num_update_transfer_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Warehouse-1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}"
    }
   ]
  },
  {
   "title": "Total Warehouse requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "num_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Stock Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "num_add_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remove Stock Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "targets": [
    {
     "expr": "num_remove_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Reservation Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "num_create_reservation_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Stock Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "num_update_stock_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warehouse Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "num_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Reservation Event Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "num_reservation_event_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "num_update_order_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Good Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "num_update_good_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Update Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "num_update_transfer_requests_total{job=\"github.com/alimitedgroup/MVP/srv/warehouse1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Order/Transfer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/order1\"}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "num_order_transfer_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Creation Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "num_order_create_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get All Order Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "num_get_all_order_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Transfer Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "num_get_transfer_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Create Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "num_transfer_create_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get All Transfer Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "num_get_all_transfer_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Order Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "num_get_order_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stock Updates Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
   "targets": [
    {
     "expr": "num_stock_updates_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Update Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 97 },
   "targets": [
    {
     "expr": "num_order_updates_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contact Warehouse Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "num_contact_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer Update Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
   "targets": [
    {
     "expr": "num_transfer_updates_requests_total{job=\"github.com/alimitedgroup/MVP/srv/order1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/catalog1\"}"
    }
   ]
  },
  {
   "title": "Get Goods Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "num_goods_requests_total{job=\"github.com/alimitedgroup/MVP/srv/catalog1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Catalog total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "targets": [
    { "expr": "num_catalog_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Set Good Data Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "targets": [
    {
     "expr": "num_good_data_requests_total{job=\"github.com/alimitedgroup/MVP/srv/catalog1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goods Quantity Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "num_goods_quantity_requests_total{job=\"github.com/alimitedgroup/MVP/srv/catalog1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Set Good Quantity Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 127 },
   "targets": [
    {
     "expr": "num_good_quantity_requests_total{job=\"github.com/alimitedgroup/MVP/srv/catalog1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Warehouses Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 127 },
   "targets": [
    {
     "expr": "num_warehouse_requests_total{job=\"github.com/alimitedgroup/MVP/srv/catalog1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Authenticator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/authenticator1\"}"
    }
   ]
  },
  {
   "title": "Auth token request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "num_token_requests_total{job=\"github.com/alimitedgroup/MVP/srv/authenticator1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"github.com/alimitedgroup/MVP/srv/api_gateway1\"}"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "description": "Number of HTTP requests per second. Grouped by instance id",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authenticated requests/s",
   "type": "timeseries",
   "description": "Number of requests to endpoints requiring authentication per second. Grouped by instance id",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 158 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}